textures.1=1
name.1=regex:.*(?i)(wooly|woolly).*

textures.2=1
name.2=jeb_

textures.3=1
colors.3=white

textures.4=2
colors.4=light_gray

textures.5=3
colors.5=gray

textures.6=4
colors.6=black

textures.7=5
colors.7=brown

textures.8=6
colors.8=red

textures.9=7
colors.9=orange

textures.10=8
colors.10=yellow

textures.11=9
colors.11=lime

textures.12=10
colors.12=green

textures.13=11
colors.13=cyan

textures.14=12
colors.14=light_blue

textures.15=13
colors.15=blue

textures.16=14
colors.16=purple

textures.17=15
colors.17=magenta

textures.18=16
colors.18=pink
