models.1=3
name.1=iregex:.*(wooly|woolly).*

models.2=2
biomeTag.2=spawns_cold_variant_farm_animals
name.2=jeb_

models.3=2
name.3=jeb_

models.4=1
biomeTag.4=spawns_cold_variant_farm_animals
nbt.4.Sheared=0

models.5=1
nbt.5.Sheared=0

models.6=1
nbt.6.Sheared=1
